DFXswiss/payment

- app/i18n/en.json
Mit Robin besprochen. Fehlende Übersetzung im Englischen aktualisiert.
> "Own-Ref" hinzugefügt

- app/i18n/de.json
- app/i18n/en.json
- app/i18n/fr.json
- app/i18n/it.json
- app/i18n/pt.json
- app/models/User.ts
- app/screens/home/HomeScreen.tsx
- app/services/AuthService.ts
> Add continue KYC

- app/i18n/de.json
- app/screens/home/HomeScreen.tsx
> KYC Button for everyone not only active user

- app/i18n/de.json
- app/i18n/en.json
- app/i18n/fr.json
- app/i18n/it.json
- app/i18n/pt.json
- app/screens/ChatBotScreen.tsx
> Add button leave

- app/components/chatbot/AnswerDatePicker.tsx
- app/components/chatbot/AnswerList.tsx
- app/models/ChatbotData.ts
- app/screens/ChatbotScreen.tsx
- app/services/ChatbotUtils.ts
- restructured parsing
- each page will be localized on the fly, there is no pre localization anymore
- date formats needed some special treatment, as they are localized too
- due to nature of delivered localizations of KYC spider there is a special functionality for joining and splitting those objects if needed
> Change language for all pages correctly

- app/screens/ChatbotScreen.tsx
- auto submitting if code is length of 4
- changed loading visualisation
> DEV-323 SMS code submit automation

- app/screens/ChatbotScreen.tsx
- app/services/ChatbotAutoAnswer.ts
- app/services/ChatbotUtils.ts
please review #119 first, as this branch builds up on bugfixes
> [DEV-422] Auto answer

- app/i18n/de.json
- app/i18n/en.json
- app/i18n/es.json
- app/i18n/fr.json
- app/i18n/it.json
- app/i18n/pt.json
- app/screens/home/RouteList.tsx
Only available in german and english ... all other languages will be added later.
> [DEV-185] SEPA Instant

- app/screens/SpecialVotingScreen.tsx
- app/screens/home/HomeScreen.tsx
- revert get stakingbalance (user state not yet defined)
- reactive get previous submitted vote
> [DEV-413] fix

- app/services/chatbot/ChatbotUtils.ts
first commit is only formatting.
the second one should be reviewed:
https://github.com/DFXswiss/payment/pull/143/commits/15f2ee7eca7b542355000470d700444f1cc7d6dd
> [DEV-567] fixing html save whitespace

- app/components/edit/KycDataEdit.tsx
- app/components/edit/UserEdit.tsx
- app/components/form/PhoneNumber.tsx
- app/models/KycData.ts
- app/models/User.ts
- app/screens/KycScreen.tsx
- app/screens/home/HomeScreen.tsx
- app/services/ApiService.ts
which is up for discussion is how we are showing blanked information to the user. I have made a proposal, but added a comment, which should be removed after a decision was made
> [DEV-519] kyc code

- app/env/Environment.dev.ts
- app/env/Environment.ts
- app/screens/LoginScreen.tsx
- app/utils/Validations.ts
depends on
- https://github.com/DFXswiss/api/pull/359
> [DEV-598] allow other blockchain login

- app/i18n/de.json
- app/i18n/en.json
- app/i18n/es.json
- app/i18n/fr.json
- app/i18n/it.json
- app/i18n/pt.json
- app/screens/KycScreen.tsx
- https://github.com/DFXswiss/api/pull/363
- https://github.com/DFXswiss/payment/pull/145
> [DEV-609] add link instructions

- app/Main.tsx
- app/config/Routes.ts
- app/i18n/de.json
- app/i18n/en.json
- app/i18n/es.json
- app/i18n/fr.json
- app/i18n/it.json
- app/i18n/pt.json
- app/models/Link.ts
- app/screens/LinkScreen.tsx
- app/services/ApiService.ts
- app/services/SignatureService.ts
- https://github.com/DFXswiss/api/pull/363
- https://github.com/DFXswiss/payment/pull/149
> [DEV-610] add link site

- app/models/BuyRoute.ts
- app/models/CryptoRoute.ts
- app/models/MinDeposit.ts
- app/models/SellRoute.ts
- app/models/StakingRoute.ts
- app/screens/home/RouteList.tsx
depends on
- https://github.com/DFXswiss/payment/pull/142 being merged first, due to all changes made to `RouteList`
- https://github.com/DFXswiss/api/pull/350
> [DEV-587] min deposit changes

- app/Main.tsx
- app/components/RouteHistory.tsx
- app/config/Routes.ts
- app/i18n/de.json
- app/i18n/en.json
- app/i18n/es.json
- app/i18n/fr.json
- app/i18n/it.json
- app/i18n/pt.json
- app/models/User.ts
- app/screens/ErrorScreen.tsx
- app/screens/LoginScreen.tsx
- app/screens/home/HomeScreen.tsx
- app/screens/home/RouteList.tsx
- app/utils/Utils.ts
> [DEV-331] improvements

- .vscode/settings.json
- app/components/edit/BuyRouteEdit.tsx
- app/components/edit/CryptoRouteEdit.tsx
- app/components/edit/SellRouteEdit.tsx
- app/models/SellRoute.ts
- app/screens/home/RouteList.tsx
> Sell route blockchain adaptions

- app/components/RouteHistory.tsx
- app/i18n/de.json
- app/i18n/en.json
- app/i18n/es.json
- app/i18n/fr.json
- app/i18n/it.json
- app/i18n/pt.json
- app/models/RouteHistory.ts
* [DEV-1454] Payment status
* [DEV-1454] change to payment status
* [DEV-1454] Refactoring payment status
[DEV-1454]: https://dfxswiss.atlassian.net/browse/DEV-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1454]: https://dfxswiss.atlassian.net/browse/DEV-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1454]: https://dfxswiss.atlassian.net/browse/DEV-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-1454] Payment status

- app/components/edit/CryptoRouteEdit.tsx
- app/models/Blockchain.ts
- app/screens/home/RouteList.tsx
* [NO-TASK] Add EVM to crypto routes and add input & output array
* [NO-TASK] refactoring
* [NO-TASK] Disable crypto button with target chains
---------
Co-authored-by: Kolibri <>
> [NO-TASK] Add EVM to crypto routes and add input & output array (#235)

- .vscode/settings.json
- app/env/Environment.dev.ts
- app/env/Environment.prd.ts
- app/env/Environment.ts
- app/models/Blockchain.ts
* [DEV-1497] added address format and signature format for LN addresses
* [DEV-1497] added new lightning blockchain
* [DEV-1497] Adapted LNURL length
---------
[DEV-1497]: https://dfxswiss.atlassian.net/browse/DEV-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1497]: https://dfxswiss.atlassian.net/browse/DEV-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1497]: https://dfxswiss.atlassian.net/browse/DEV-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-1497] Lightning addresses (#234)

- app/screens/AdminScreen.tsx
- app/screens/ChatbotScreen.tsx
- app/screens/ErrorScreen.tsx
- app/screens/GtcScreen.tsx
- app/screens/LinkScreen.tsx
- app/screens/LoginScreen.tsx
- app/screens/NotFoundScreen.tsx
- app/screens/home/HomeScreen.tsx
- app/screens/home/RouteList.tsx
- app/screens/home/TransactionHistory.tsx
- package-lock.json
* [DEV-2511] Add redirect to services
* [DEV-2511] Refactoring
---------
Co-authored-by: Kolibri <>
[DEV-2511]: https://dfxswiss.atlassian.net/browse/DEV-2511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2511]: https://dfxswiss.atlassian.net/browse/DEV-2511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-2511] Add redirect to services (#266)
